collection_name: smart_home_agent
user_preferences_collection_name: user_preferences
k: 3
data_path: data
md5_hex_store: md5_milvus.txt
allow_knowledge_file_type: ["txt", "pdf"]
chunk_size: 200
chunk_overlap: 20
separators: ["\n\n", "\n", ".", "!", "?", "。", "！", "？", " ", ""]
