"""
Huawei IoTDA Device Simulator
Runs 7 virtual devices over MQTT TLS, receiving sync commands and reporting properties.

Usage:
    python scripts/device_simulator.py

Requires:
    - config/iotda_devices.yml (generated by scripts/iotda_provision.py)
    - .env with IOTDA_ENDPOINT
"""

from __future__ import annotations

import hashlib
import hmac
import json
import logging
import ssl
import time
from pathlib import Path

import paho.mqtt.client as mqtt
import yaml

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s] %(levelname)s %(name)s: %(message)s",
    datefmt="%H:%M:%S",
)

DEVICE_CONFIG_PATH = Path(__file__).parent.parent / "config" / "iotda_devices.yml"


def _mqtt_password(device_secret: str, timestamp: str) -> str:
    """IoTDA MQTT auth: HMAC-SHA256(key=timestamp, msg=device_secret)."""
    return hmac.new(
        timestamp.encode(),
        device_secret.encode(),
        hashlib.sha256,
    ).hexdigest()


class DeviceSimulator:
    """Base class for a virtual IoTDA device connected over MQTT TLS."""

    SERVICE_ID: str = ""
    COMMAND_NAME: str = ""

    def __init__(
        self,
        device_id: str,
        device_secret: str,
        endpoint: str,
        room: str = "",
        device_type: str = "",
    ):
        self.device_id = device_id
        self.room = room
        self.device_type = device_type
        self._endpoint = endpoint
        self._logger = logging.getLogger(f"[{room}-{device_type}]")
        self._state: dict = {}

        # IoTDA expects YYYYMMDDhh (UTC) format; password = HMAC-SHA256(key=timestamp, msg=secret)
        import datetime
        timestamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%d%H")
        client_id = f"{device_id}_0_0_{timestamp}"
        password = _mqtt_password(device_secret, timestamp)

        # paho-mqtt >= 2.0.0: requires callback_api_version
        # Use VERSION1 for backward-compatible callback signatures (rc as int, etc.)
        self._mqtt = mqtt.Client(
            callback_api_version=mqtt.CallbackAPIVersion.VERSION1,
            client_id=client_id,
            protocol=mqtt.MQTTv311,
            reconnect_on_failure=True,
        )

        self._mqtt.username_pw_set(username=device_id, password=password)
        self._mqtt.tls_set(cert_reqs=ssl.CERT_REQUIRED)
        self._mqtt.on_connect = self._on_connect
        self._mqtt.on_disconnect = self._on_disconnect
        self._mqtt.on_message = self._on_message

    def connect(self):
        self._mqtt.connect(host=self._endpoint, port=8883, keepalive=60)
        self._mqtt.loop_start()

    def disconnect(self):
        self._mqtt.loop_stop()
        self._mqtt.disconnect()

    def _on_connect(self, client, userdata, flags, rc):
        if rc == 0:
            topic = f"$oc/devices/{self.device_id}/sys/commands/#"
            client.subscribe(topic, qos=1)
            self._logger.info(f"Connected, subscribed to {topic}")
            self._report_properties()
        else:
            self._logger.warning(f"Connection failed rc={rc}")

    def _on_disconnect(self, client, userdata, rc):
        self._logger.warning(f"Disconnected rc={rc}, will retry...")

    def _on_message(self, client, userdata, msg):
        try:
            payload = json.loads(msg.payload.decode())
        except json.JSONDecodeError:
            self._logger.error(f"Invalid JSON: {msg.payload}")
            return

        # command_id is in the topic: .../sys/commands/{command_id}
        topic_parts = msg.topic.split("/")
        command_id = topic_parts[-1] if topic_parts[-1] != "commands" else payload.get("command_id", "")
        command_name = payload.get("command_name", "")
        paras = payload.get("paras", {})

        self._logger.info(f"Command received: {command_name} {paras}")

        if command_name == self.COMMAND_NAME:
            self.handle_command(paras)
        else:
            self._logger.warning(f"Unknown command: {command_name}")
            self._send_command_response(command_id, command_name, result_code=1)
            self._report_properties()
            return

        self._send_command_response(command_id, command_name)
        self._report_properties()

    def handle_command(self, paras: dict):
        raise NotImplementedError

    def _report_properties(self):
        topic = f"$oc/devices/{self.device_id}/sys/properties/report"
        payload = {
            "services": [{
                "service_id": self.SERVICE_ID,
                "properties": self._state,
                "event_time": time.strftime("%Y%m%dT%H%M%SZ", time.gmtime()),
            }]
        }
        self._mqtt.publish(topic, json.dumps(payload), qos=1)
        self._logger.info(f"Properties reported: {self._state}")

    def _send_command_response(self, command_id: str, command_name: str, result_code: int = 0):
        if not command_id:
            return
        topic = f"$oc/devices/{self.device_id}/sys/commands/{command_id}/response"
        payload = {
            "result_code": result_code,
            "response_name": f"{command_name}Response",
            "paras": {"result": "success" if result_code == 0 else "unknown_command"},
        }
        self._mqtt.publish(topic, json.dumps(payload), qos=1)


# ── Device subclasses ───────────────────────────────────────────────────────

class LightSimulator(DeviceSimulator):
    SERVICE_ID = "LightControl"
    COMMAND_NAME = "SetLight"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._state = {"on": False, "color": "白色", "brightness": 0}

    def handle_command(self, paras: dict):
        self._state["on"] = bool(paras.get("on", False))
        self._state["color"] = paras.get("color", self._state["color"])
        self._state["brightness"] = int(paras.get("brightness", self._state["brightness"]))


class ACSimulator(DeviceSimulator):
    SERVICE_ID = "ACControl"
    COMMAND_NAME = "SetTemperature"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._state = {"on": False, "temperature": 26}

    def handle_command(self, paras: dict):
        self._state["on"] = bool(paras.get("on", self._state["on"]))
        self._state["temperature"] = int(paras.get("temperature", self._state["temperature"]))


class CurtainSimulator(DeviceSimulator):
    SERVICE_ID = "CurtainControl"
    COMMAND_NAME = "SetCurtain"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._state = {"position": "closed"}

    def handle_command(self, paras: dict):
        action = paras.get("action", "stop")
        self._state["position"] = {"open": "open", "close": "closed", "stop": "stopped"}.get(
            action, "stopped"
        )


class VacuumSimulator(DeviceSimulator):
    SERVICE_ID = "VacuumControl"
    COMMAND_NAME = "StartVacuum"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._state = {"status": "idle", "room": ""}

    def handle_command(self, paras: dict):
        self._state["status"] = "working"
        self._state["room"] = paras.get("room", "全屋")


# ── Entry point ─────────────────────────────────────────────────────────────

_SIMULATOR_MAP: dict[str, type[DeviceSimulator]] = {
    "light": LightSimulator,
    "ac": ACSimulator,
    "curtain": CurtainSimulator,
    "vacuum": VacuumSimulator,
}


def main():
    import os
    from dotenv import load_dotenv
    load_dotenv()

    endpoint = os.environ.get("IOTDA_DEVICE_ENDPOINT") or os.environ["IOTDA_ENDPOINT"]

    with open(DEVICE_CONFIG_PATH, encoding="utf-8") as f:
        config = yaml.safe_load(f)

    if not config:
        logging.error("Device config is empty or missing: %s", DEVICE_CONFIG_PATH)
        return

    simulators: list[DeviceSimulator] = []
    for room, types in config.items():
        for dtype, info in types.items():
            cls = _SIMULATOR_MAP.get(dtype)
            if not cls:
                continue
            try:
                sim = cls(
                    device_id=info["device_id"],
                    device_secret=info["device_secret"],
                    endpoint=endpoint,
                    room=room,
                    device_type=dtype,
                )
                simulators.append(sim)
            except KeyError as e:
                logging.warning("Skipping %s/%s — missing key %s in config", room, dtype, e)

    logging.info(f"Starting {len(simulators)} device simulators...")
    for sim in simulators:
        sim.connect()

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        logging.info("Shutting down simulators...")
        for sim in simulators:
            sim.disconnect()


if __name__ == "__main__":
    main()
